---
title: "| Data Science With an Eye Towards Sustainability    \n| P7: Project Check-In and Research Questions Update\n"
author: "INSERT STUDENT NAMES HERE"
output:
  bookdown::html_document2:
    split_by: none
    toc: no

---


 

It is time for another project checkpoint. By now, your research questions should be significantly narrowed, and you should be well on your way to developing some visualizations to answer at least some of the research questions. **Each group should hand in one html document for the following exercises.**

\

# Names & Workflow

List all group members. Discuss a plan for completing this assignment. How will you put together your shared Rmd? How will you divide the work? When will you meet to work on the assignment? Write this down in your Rmd.

Also, if you are using one, write down your GitHub repository.

\

# Team Health and Progress

Please take a few minutes to reflect collectively on how things have been going so far in terms of working together as a team. What has worked well? What hasn't? Are there work flow changes you want to make for the remainder of the project?

\

# Refined Research Questions

Please specify your updated research question(s) here. At this point, I am expecting 1-4 research questions that are more closely connected.

\

# Connections to Sustainability

How are your research questions connected to sustainability? What are your personal learning goals related to sustainability for this project? You may wish to refer back to the [UN Sustainable Development Goals](https://sdgs.un.org/goals), the [Inner Development Goals](https://innerdevelopmentgoals.org/), and the [Engineering for One Planet](https://engineeringforoneplanet.org/wp-content/uploads/EOP_Framework_2023.pdf?), [Six Pillars of Climate Justice](https://centerclimatejustice.universityofcalifornia.edu/what-is-climate-justice/), and [Just Transition Principles](https://climatejusticealliance.org/just-transition/) frameworks. As a team, what sustainability background, analysis, and  storytellling do you want to include in the scope of your project and in your final artifacts?


\

# Data

Identify the data sets you are using to explore the research questions above. These data sets may already be in csv form, you may acquire them (e.g., scraped with rvest, via public API, or from an SQL database), or you may plan on collecting some extra data. For each data set, summarize the following:

- data source
- data description - what's being measured?
- data limitations (eg: are the data recent? do they contain all variables you might want?)
- data dimensions - how much data do you have?
- how might the data be joined with other data you have?

\

# Research Question 1

Restate research question 1. Construct 3-4 relevant visualizations that provide insight on / help answer this question and piece these together to tell a short story. For each visualization, 1-2 sentences will suffice.

\

# Research Question 2 (and possibly 3 and 4)

Repeat the previous exercise for your second and possibly third or fourth research questions. Make a new section for each question.

\

# Next Steps

Identify next steps in your analysis. Do you need additional data? Do you need to do more cleaning or wrangling? Do you need to do some statistical modeling and inference? What additional visualizations would be helpful? How are the stories coming together? 

\

# Contributions

Summarize each group member's specific contributions to this checkpoint assignment.

