---
title: "QV_P6_Viz"
output: html_document
date: "2026-04-03"
---

```{r setup, include=FALSE}

library(tidyverse)
library(tidycensus)
library(sf)
library(tmap)
library(DT)
library(readr)
library(rvest)
library(ggplot2)
library(chromote)
library(tigris)
library(dplyr)
knitr::opts_chunk$set(echo = TRUE)
```

## Project Sunroof Data

-   Spatial viz for sun exposure & for current solar installations

    -   expand to spatial viz for average income per captia, etc

Copy the following code & library commands into the larger P6 file!

```{r}
#pulling from sunroof file
project_sunroof_census_tract <- read_csv("~/Documents/GitHub/solar-incentive-adoption/Solar-Project/project-sunroof-city.csv", 
    col_types = cols(state_name = col_factor(levels = c("Alabama", 
        "Alaska", "Arizona", "Arkansas", 
        "California", "Colorado", "Connecticut", 
        "Delaware", "Florida", "Georgia", 
        "Hawaii", "Idaho", "Illinois", "Indiana", 
        "Iowa", "Kansas", "Kentucky", "Louisiana", 
        "Maine", "Maryland", "Massachusetts", 
        "Michigan", "Minnesota", "Mississippi", 
        "Missouri", "Montana", "Nebraska", 
        "Nevada", "New Hampshire", "New Jersey", 
        "New Mexico", "New York", "North Carolina", 
        "North Dakota", "Ohio", "Oklahoma", 
        "Oregon", "Pennsylvania", "Rhode Island", 
        "South Carolina", "South Dakota", 
        "Tennessee", "Texas", "Utah", "Vermont", 
        "Virginia", "Washington", "West Virginia", 
        "Wisconsin", "Wyoming"))))
wrangled_sunroof <- project_sunroof_census_tract |>
  filter(state_name == "Massachusetts") |>
  drop_na(count_qualified)

#scraping city/town data from wikipedia - population
url<-"https://en.wikipedia.org/wiki/List_of_municipalities_in_Massachusetts"
webpage<-rvest::read_html(url)
city <- webpage |>
  html_nodes(".static-row-numbers td:nth-child(1)") |>
  html_text2() 
county <- webpage |>
  html_nodes(".static-row-numbers td:nth-child(3)") |>
  html_text2() 
type <- webpage |>
  html_nodes(".static-row-numbers td:nth-child(2)") |>
  html_text2() 
pop <- webpage |>
  html_nodes(".static-row-numbers td:nth-child(5)") |>
  html_text2() 
mass_city <- tibble(county=county,city=city, pop_2020=pop, type=type)
mass_city <- mass_city|>
 # grepl("seat", county)
  mutate(county=sub("(seat)"," ", county))|>
  mutate(county=sub("\\("," ", county))|>
  mutate(county=sub("\\)"," ", county))

#scraping city/town median income data from wikipedia
url<-"https://en.wikipedia.org/wiki/List_of_Massachusetts_locations_by_per_capita_income"
webpage<-rvest::read_html(url)

town <- webpage |>
  html_nodes("td:nth-child(2)") |>
  html_text2() 
town <- tibble(town=town) 
town2 <- town[16:356,c(1)]

median_income <- webpage |>
  html_nodes("td:nth-child(5)") |>
  html_text2() 
median_income <- tibble(median_income=median_income)
median_income2 <- median_income[16:356,c(1)]

median_income_town <- town2 |>
  bind_cols(town2, median_income2) |>
  janitor::clean_names() |>
  mutate(town=town_1, median_income_per_capita=as.numeric(gsub("[$, ]", "" , median_income)))|>
  select(town, median_income_per_capita)

#joining data frames
sunroof_towns <- left_join(wrangled_sunroof, median_income_town, by = c("region_name"="town")) |> 
  select(region_name, count_qualified, percent_covered, percent_qualified, number_of_panels_median, number_of_panels_total, existing_installs_count, median_income_per_capita) |>
  left_join(mass_city, by=c("region_name"="city"))|>
  mutate(pop_2020_num = as.numeric(gsub("[, ]", "" , pop_2020))) |>
  drop_na() 

#attempting to normalize by population...
sunroof_towns$existing_installs_per_capita <- (sunroof_towns$existing_installs_count/sunroof_towns$pop_2020_num)


```

```{r}

#getting spatial geometry data for each town/city in MA

options(tigris_class = "sf")
ma_municipalities <- county_subdivisions(state = "MA", cb = TRUE)

ma_towns_geo <- ma_municipalities |>
  select(NAME, GEOID, geometry) |>
  rename(town_name = NAME)

plot(st_geometry(ma_towns_geo), main = "Massachusetts Cities and Towns")

#joining with sunroof_towns

```

```{r}
p1 <- ggplot(sunroof_towns, aes(x=median_income_per_capita,y=percent_qualified, fill=region_name)) +
  geom_point() +
  geom_smooth(method="lm",se=FALSE)+
  ggtitle("Median Income per Capita vs Percent Qualified for Rooftop Solar", subtitle="Broken down by town/city in MA" )+
  labs(x="Median Income per Capita ($)", y="Percent Qualified")
ggplotly(p1)

p2 <- ggplot(sunroof_towns, aes(x=median_income_per_capita,y=number_of_panels_median, fill=region_name)) +
  geom_point() +
  geom_smooth(method="lm",se=FALSE) +
  ggtitle("Median Income per Capita vs Median Number of Installed Rooftop Solar Panels", subtitle="Broken down by town/city in MA")+
  labs(x="Median Income per Capita ($)", y="Number of Panels Median")
ggplotly(p2)

p3 <- ggplot(sunroof_towns, aes(x=median_income_per_capita,y=existing_installs_count, fill=region_name)) +
  geom_point() +
  geom_smooth(method="lm",se=FALSE) +
  ggtitle("Median Income per Capita vs Existing Rooftop Solar Installations", subtitle="Broken down by town/city in MA")+
  labs(x="Median Income per Capita ($)", y="Existing Installs")
ggplotly(p3)


```

```{r}
#scraping inscentive types from sunroof site
url <- "https://sunroof.withgoogle.com/data-explorer/place/ChIJ6duAGcKF44kRcPcl1AELMAs/"
b <-ChromoteSession$new()
b$Page$navigate(url)
Sys.sleep(5)
webpage3 <- read_html(b$Runtime$evaluate("document.documentElement.outerHTML")$result$value)
needham_inscentives <- webpage3 |>
  html_nodes(".place-incentives-content .incentive-wide-column") |>
  html_text2() 
```

Prices of Solar Installations and Electricity over time

```{r}
#importing datasets

solar_inst_costs <- read_csv("~/Documents/GitHub/solar-incentive-adoption/Solar-Project/solar-installed-system-cost-analysis_residential.csv", 
    col_types = cols(`Cost Type` = col_factor(levels = c("Hardware", 
        "Soft Costs")))) |>
  select(Year, Value, `Cost Type`)

#from NREL

elec_price_03_26 <- read_csv("~/Documents/GitHub/solar-incentive-adoption/Solar-Project/electricity-avg-price-2003-2026.csv", 
    col_types = cols(observation_date = col_date(format = "%Y-%m-%d"))) |>
  mutate(cost = APU000072610) |>
  drop_na()
#from federal reserve

```

```{r}
#plotting
ggplot(elec_price_03_26, aes(x=observation_date, y=cost, theme(size=0.1)))+
  geom_line() +
  labs(y="Cost ($) per kWh", x=NULL, title="Average Electricity Cost ($) per Kilowatt-Hour in U.S. City", subtitle="Source: U.S. Bureau of Labor Statistics via FRED")+
  theme_clean()

ggplot(solar_inst_costs, aes(x=Year, y=Value, fill=`Cost Type`))+
  geom_col()+
  scale_y_continuous()+
  theme_clean()+
  labs(x=NULL, y="Total Estimated Installation Cost ($) per Watt", title="Estimated Installation Cost ($) of Residential Rooftop (US)", subtitle="Source: NREL Solar Installed System Cost Analysis", caption="Hardware costs include PV modules, inverters. \n Soft costs include import fees tarifs, labor, permits, etc.")

  
```

Code Archive:

```{r, eval=FALSE}
#getting the geography and location data for the counties in MA - this takes forever to run for some reason
mass_tracts <- tidycensus::get_acs(state = "MA",
                          county = c("Barnstable", "Berkshire", "Bristol", "Dukes", "Essex", "Franklin", "Hampden", "Hampshire", "Middlesex", "Nantucket", "Norfolk", "Plymouth", "Suffolk", "Worcester"),
                          geography = "tract",
                          variables = c("B02001_002E","B02001_003E","B01003_001E","B19013_001", "B07011_001"),
                          year=2024,
                          geometry = TRUE)

# figure out how to identify what geo id structure i have and how to change it
# want averages per town

#joining mass_tracts w/ wrangled_sunroof by the geoid & region_name variables, keeping all the tags from mass_tracts to get a complete map

sunroof_tracts <- left_join(mass_tracts, wrangled_sunroof, by = c("GEOID"="region_name"))


####

census_vars <- c(
  population = "B01001_001",
  median_income = "B19013_001"
)
mass_towns <- tidycensus::get_acs(
  geography = "place",
  variables = census_vars,
  state = "MA",
  year = 2024,
  survey = "acs5",
  geometry = TRUE,
  output = "wide") |>
  mutate(city_name = str_remove(NAME, " (town|city|CDP|Town).*")) |>
  select(GEOID, city_name, populationE, median_incomeE, geometry)
```
